/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2019-01-09 14:31:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import by.vsu.course.*;
import by.vsu.teacher.*;
import by.vsu.user.*;
import by.vsu.dbGeneral.*;

public final class editCourse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1542609989770L));
    _jspx_dependants.put("jar:file:/C:/Users/Алексей/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/lab5test/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("by.vsu.course");
    _jspx_imports_packages.add("by.vsu.teacher");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("by.vsu.user");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("by.vsu.dbGeneral");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Course object = (Course)request.getAttribute("object");
	HttpSession ses = request.getSession();
	User obj = (User)ses.getAttribute("user");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Lb 5</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.5.0/css/all.css\" integrity=\"sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU\" crossorigin=\"anonymous\">\r\n");
      out.write("    <style>\r\n");
      out.write("       * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        .btn {\r\n");
      out.write("            height: fit-content;\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 10px 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            background-color: #ffdb4d;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #000;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            background-color: #fdd32a;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            color: #ffdb4d;\r\n");
      out.write("        }\r\n");
      out.write("        .header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("            height: 8vh;\r\n");
      out.write("            background-color: rgb(79, 30, 128);\r\n");
      out.write("            box-shadow: 0px 4px 8px rgba(79, 30, 128,0.95);\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .nav, .auth {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            justify-content: flex-start;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .nav__item, .auth a {\r\n");
      out.write("            margin-right: 15px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .teacher__form {\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("        .form__input {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input, select {\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            padding: 11px 0;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background-color: #eee;\r\n");
      out.write("            padding-left: 20px;\r\n");
      out.write("            padding-right: 20px;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .teacher {\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            padding-top: 26px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .teacher h2 {\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .teacher .form__input {\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <h1 class=\"logo\">Lb 5</h1>\r\n");
      out.write("        <nav class=\"nav\">\r\n");
      out.write("        \t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /view/editCourse.jsp(101,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest( obj != null && obj.getRole_id() == 1);
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t    <a href=\"/lab5test/ListUsersServlet\" class=\"nav__item btn\">users</a>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("            <a href=\"/lab5test/index.html\" class=\"nav__item btn\">teachers</a>\r\n");
      out.write("            <a href=\"/lab5test/ListCoursesServlet\" class=\"nav__item btn\">courses</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"auth\">\r\n");
      out.write("\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /view/editCourse.jsp(108,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest( obj == null );
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t    <a href=\"view/login.html\" class=\"reg btn\">Войти</a>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f2_reused = false;
      try {
        _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f2.setParent(null);
        // /view/editCourse.jsp(111,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f2.setTest( obj != null );
        int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
        if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t    <h2 class=\"login\">");
            out.print( obj.getLogin() );
            out.write("</h2>\r\n");
            out.write("\t\t\t    <a href=\"/lab5test/LogoutServlet\" class=\"reg btn\">Выйти</a>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
        _jspx_th_c_005fif_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
      }
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <section class=\"teacher\">\r\n");
      out.write("        <h3 class=\"teacher__header\">Teachers</h3>\r\n");
      out.write("        <form class=\"teacher__form\" action=\"/lab5test/SaveCourseServlet\" method=\"POST\">\r\n");
      out.write("        \t<div class=\"form__input\" style=\"display: none\">\r\n");
      out.write("                <label for=\"id\">\r\n");
      out.write("                    Id:\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <input id=\"id\" type=\"text\" name=\"id\" value=\"");
      out.print( object != null ? object.getId() : "" );
      out.write("\">   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form__input\">\r\n");
      out.write("                <label for=\"title\">\r\n");
      out.write("                    Название курса:\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <input id=\"title\" type=\"text\" name=\"title\"  placeholder=\"Введите имя\" value=\"");
      out.print( object != null ? object.getTitle() : "" );
      out.write("\">   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form__input\">\r\n");
      out.write("                <label for=\"teacher\">\r\n");
      out.write("                    Преподаватель\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <select id=\"teacher\" name=\"teacher\">\r\n");
      out.write("   \t\t\t\t\t\t<option ");
      out.print( object == null ? "selected" : "" );
      out.write(" value=0>Выберите преподавателя</option>\r\n");
      out.write("   \t\t\t\t\t\t");

			                 for(Teacher item : Teachers.select("id")) {
			             
      out.write("\r\n");
      out.write("   \t\t\t\t\t\t\t<option ");
      out.print( object != null && object.getTeacherId() == item.getId() ? "selected" : "" );
      out.write(" value=");
      out.print( item.getId() );
      out.write('>');
      out.print( item.getFullName()  );
      out.write("</option>\r\n");
      out.write(" \t\t\t\t\t\t");

			                 }
			             
      out.write(" \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t</select>   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form__input\">\r\n");
      out.write("                <label for=\"specialty\">\r\n");
      out.write("                    Специальность\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <select id=\"specialty\" name=\"specialty\">\r\n");
      out.write("   \t\t\t\t\t\t<option ");
      out.print( object == null ? "selected" : "" );
      out.write(" value=0>Выберите специальночть</option>\r\n");
      out.write("   \t\t\t\t\t\t");

			                 for(Table item : Specialty.select()) {
			             
      out.write("\r\n");
      out.write("   \t\t\t\t\t\t\t<option ");
      out.print( object != null && object.getSpecialtyId() == item.getId() ? "selected" : "" );
      out.write(" value=");
      out.print( item.getId() );
      out.write('>');
      out.print( item.getTitle()  );
      out.write("</option>\r\n");
      out.write(" \t\t\t\t\t\t");

			                 }
			             
      out.write(" \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t</select>   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form__input\">\r\n");
      out.write("                <label for=\"numberCourse\">\r\n");
      out.write("                    Номер курса\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <input id=\"numberCourse\" type=\"text\" name=\"numberCourse\" placeholder=\"Введите номер курса\"  value=\"");
      out.print( object != null ? object.getNumberCourse() : "" );
      out.write("\">   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("           <div class=\"form__input\">\r\n");
      out.write("                <label for=\"semester\">\r\n");
      out.write("                    Семестер\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <select name=\"semester\">\r\n");
      out.write("   \t\t\t\t\t\t<option ");
      out.print( object == null ? "selected" : "" );
      out.write(" value=0>Выберите семестер</option>\r\n");
      out.write("   \t\t\t\t\t\t<option ");
      out.print( object != null && object.getSemester() == 1 ? "selected" : "" );
      out.write(" value=\"1\">1</option>\r\n");
      out.write("   \t\t\t\t\t\t<option ");
      out.print( object != null && object.getSemester() == 2 ? "selected" : "" );
      out.write(" value=\"2\">2</option>\r\n");
      out.write("  \t\t\t\t\t</select>   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form__input\">\r\n");
      out.write("                <label for=\"countStudents\">\r\n");
      out.write("                    Количество студентов\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <input id=\"countStudents\" type=\"text\" name=\"countStudents\" placeholder=\"Введите кол-во студентов\"  value=\"");
      out.print( object != null ? object.getCountStudents() : "" );
      out.write("\">   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form__input\">\r\n");
      out.write("                <label for=\"lectureHours\">\r\n");
      out.write("                    lectureHours\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <input id=\"lectureHours\" type=\"text\" name=\"lectureHours\" placeholder=\"Введите lectureHours\"  value=\"");
      out.print( object != null ? object.getLectureHours() : "" );
      out.write("\">   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form__input\">\r\n");
      out.write("                <label for=\"practicalHours\">\r\n");
      out.write("                    lectureHours\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <input id=\"practicalHours\" type=\"text\" name=\"practicalHours\" placeholder=\"Введите practicalHours\"  value=\"");
      out.print( object != null ? object.getPracticalHours() : "" );
      out.write("\">   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form__input\">\r\n");
      out.write("                <label for=\"laborotoryHours\">\r\n");
      out.write("                    lectureHours\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <input id=\"laborotoryHours\" type=\"text\" name=\"laborotoryHours\" placeholder=\"Введите laborotoryHours\"  value=\"");
      out.print( object != null ? object.getLaborotoryHours() : "" );
      out.write("\">   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form__input\">\r\n");
      out.write("                <label for=\"credit\">\r\n");
      out.write("                    credit\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <input id=\"credit\" type=\"checkbox\" name=\"credit\" ");
      out.print( object != null && object.isCredit() ? "checked" : "" );
      out.write(">   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form__input\">\r\n");
      out.write("                <label for=\"exam\">\r\n");
      out.write("                    exam\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <input id=\"exam\" type=\"checkbox\" name=\"exam\" ");
      out.print( object != null && object.isExam() ? "checked" : "" );
      out.write(">   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form__input\">\r\n");
      out.write("                <label for=\"countTests\">\r\n");
      out.write("                    countTests\r\n");
      out.write("                </label>\r\n");
      out.write("                <div class=\"input\">\r\n");
      out.write("                    <input id=\"countTests\" type=\"text\" name=\"countTests\" placeholder=\"Введите countTests\"  value=\"");
      out.print( object != null ? object.getCountTests() : "" );
      out.write("\">   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"teacher__save\">\r\n");
      out.write("\t            <BUTTON class=\"btn\" type=\"submit\">Сохранить</BUTTON>\r\n");
      out.write("\t        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
